### ISSUE TITLE
Crash report for date parsing 

### ISSUE THREAD

**Issue by casolorz** [mopub/mopub-volley#7]
I'm getting a crash on Fabric, not very often, and it appears to come from this package. 

```
Fatal Exception: java.lang.AssertionError: No NameTypeIndex match for SHORT_STANDARD
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex(TimeZoneNamesImpl.java:724)
       at android.icu.impl.TimeZoneNamesImpl$ZNames.getName(TimeZoneNamesImpl.java:790)
       at android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName(TimeZoneNamesImpl.java:183)
       at android.icu.text.TimeZoneNames.getDisplayName(TimeZoneNames.java:261)
       at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1296)
       at java.text.SimpleDateFormat.format(SimpleDateFormat.java:1004)
       at java.text.SimpleDateFormat.format(SimpleDateFormat.java:974)
       at java.text.DateFormat.format(DateFormat.java:341)
       at com.mopub.volley.toolbox.HttpHeaderParser.formatEpochAsRfc1123(HttpHeaderParser.java:152)
       at com.mopub.volley.toolbox.BasicNetwork.getCacheHeaders(BasicNetwork.java:256)
       at com.mopub.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:130)
       at com.mopub.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:120)
       at com.mopub.volley.NetworkDispatcher.run(NetworkDispatcher.java:87)
```

I have no idea how to reproduce. This is with `com.mopub:mopub-sdk:5.5.0`.

**Comment by Khang-NT** [comment]
+1 here

**Comment by BianconeroIle** [comment]
Still valid.

**Comment by BianconeroIle** [comment]
+1
